version: "3.4"


services:
  api:
    image: reactioncommerce/reaction:latest
    depends_on:
      - mongo
    env_file:
      - .api.env
    ports:
      - "3000:3000"

  storefront:
    image: reactioncommerce/example-storefront:latest
    env_file:
      - ./.storefront.env
    ports:
      - "4000:4000"

  admin:
    image: reactioncommerce/admin:latest
    env_file:
      - ./.admin.env
    ports:
      - "4080:4080"
      - "9231:9229"

  mongo:
    image: mongo:4.4.0
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    ports:
      - "27017:27017"
    volumes:
      - mongo-db4demo:/data/db
    healthcheck: # re-run rs.initiate() after startup if it failed.
      test: test $$(echo "rs.status().ok || rs.initiate().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s

volumes:
  mongo-db4demo:
